spring.application.name=Weather-App
weather.api.key=bd41b0cc806e413684293650261303
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json